// GENERATED by `make contracts` (backend/copilot/contracts/codegen.py). Do not edit.
// Canonical stream payloads come from Person C's simulator/schemas.py;
// envelope + hub messages from backend/copilot/contracts. Changes are additive only.
/* eslint-disable */

export const CONTRACT_VERSION = "1.2.0";
export const EVENT_CATALOGUE = ["seatbelt_unfastened", "seatbelt_fastened", "proximity_alert", "fatigue_alert", "tip_over_warning", "v2v_collision_risk", "v2i_suggestion", "anomaly_detected", "maintenance_due", "weather_change", "task_reordered", "working_risk_changed", "source_changed", "low_fuel", "engine_fault", "emergency_stop", "action_pending", "action_confirmed", "action_cancelled", "action_failed", "incident_created", "work_order_created", "training_booked"] as const;
export const HUB_EVENT_KINDS = ["source_changed", "low_fuel", "engine_fault", "emergency_stop", "action_pending", "action_confirmed", "action_cancelled", "action_failed", "incident_created", "work_order_created", "training_booked"] as const;
export const SEVERITIES = ["info", "low", "medium", "high", "critical"] as const;
export type EventKind = (typeof EVENT_CATALOGUE)[number];
export type Severity = (typeof SEVERITIES)[number];

export interface AssistantRequest {
  surface: "cab" | "command" | "owner" | "training" | "ar";
  message: string;
  machine_id?: string | null;
  operator_id?: string | null;
  conversation_id?: string | null;
}

export interface Citation {
  kind: "manual" | "protocol";
  doc_id: string;
  title: string;
  page?: number | null;
  step?: number | null;
  quote: string;
  section?: string | null;
  citation?: string | null;
}

/** Hub -> source, only to sources whose source_hello set accepts_control. */
export interface Control {
  type: "control";
  command_id: string;
  command: string;
  args?: Record<string, unknown>;
  issued_by: string;
}

export interface ControlAck {
  type: "control_ack";
  command_id: string;
  ok: boolean;
  error?: string | null;
}

export interface Heartbeat {
  /** Hub-global; strictly increasing per connection; may skip. */
  seq: number;
  /** Hub run id. A change means: drop state, wait for snapshot. */
  epoch: string;
  /** ISO-8601 UTC, millisecond precision, when the hub published. */
  hub_ts: string;
  type: "heartbeat";
  last_seq: number;
  last_rseq: number;
  clients: number;
  sources?: SourceInfo[];
}

export interface Hello {
  /** Hub-global; strictly increasing per connection; may skip. */
  seq: number;
  /** Hub run id. A change means: drop state, wait for snapshot. */
  epoch: string;
  /** ISO-8601 UTC, millisecond precision, when the hub published. */
  hub_ts: string;
  type: "hello";
  server: string;
  contract_version: string;
  /** True when since_rseq was honoured and missed events follow. */
  resumed: boolean;
  sources?: SourceInfo[];
  features?: Record<string, string>;
}

/** C's event + envelope + hub annotations (all optional, only present when set). */
export interface LiveEvent {
  /** Hub-global; strictly increasing per connection; may skip. */
  seq: number;
  /** Hub run id. A change means: drop state, wait for snapshot. */
  epoch: string;
  /** ISO-8601 UTC, millisecond precision, when the hub published. */
  hub_ts: string;
  /** Contiguous per epoch over reliable messages; a gap means loss. */
  rseq: number;
  type: "event";
  id: string;
  ts: string;
  event: string;
  severity: "info" | "low" | "medium" | "high" | "critical";
  machine_id?: string | null;
  source: "simulator" | "scenario" | "webcam" | "rules" | "ml" | "v2v" | "v2i";
  message: string;
  data?: Record<string, unknown>;
  /** Which ingest source produced it. */
  source_id?: string | null;
  /** True when ts is >30 s older than hub receipt. */
  stale?: boolean | null;
  /** 1.2.0: matching site protocol, steps verbatim. */
  protocol?: ProtocolRef | null;
}

/** C's machine_state + envelope. */
export interface LiveMachineState {
  /** Hub-global; strictly increasing per connection; may skip. */
  seq: number;
  /** Hub run id. A change means: drop state, wait for snapshot. */
  epoch: string;
  /** ISO-8601 UTC, millisecond precision, when the hub published. */
  hub_ts: string;
  type: "machine_state";
  ts: string;
  machine_id: string;
  model: string;
  machine_type: "excavator" | "wheel_loader" | "dozer" | "truck" | "grader";
  operator_id: string;
  status: "working" | "idle" | "travelling" | "off";
  pos: Pos;
  heading_deg: number;
  speed_mps: number;
  intent: "dig" | "swing_left" | "swing_right" | "dump" | "travel_forward" | "reverse" | "idle" | "push" | "grade";
  engine_on: boolean;
  engine_hours: number;
  fuel_level_pct: number;
  fuel_used_l: number;
  load_cycles: number;
  idle_min: number;
  seatbelt: "fastened" | "unfastened";
  boom_angle_deg: number;
  stick_angle_deg: number;
  swing_angle_deg: number;
  payload_kg: number;
  hydraulic_temp_c: number;
  coolant_temp_c: number;
  pitch_deg: number;
  roll_deg: number;
  tip_over_margin: number;
  bubble: "green" | "amber" | "red";
  nearest_person_m: number;
  fatigue_score: number;
  fault_codes?: string[];
  zone: string;
  task_id?: string | null;
  task_progress: number;
  task_eta_min: number;
}

/** C's worker_state + envelope. */
export interface LiveWorkerState {
  /** Hub-global; strictly increasing per connection; may skip. */
  seq: number;
  /** Hub run id. A change means: drop state, wait for snapshot. */
  epoch: string;
  /** ISO-8601 UTC, millisecond precision, when the hub published. */
  hub_ts: string;
  type: "worker_state";
  ts: string;
  worker_id: string;
  pos: Pos;
  zone: string;
}

/** One per machine per second. Contract section 5.1. */
export interface MachineState {
  type: "machine_state";
  ts: string;
  machine_id: string;
  model: string;
  machine_type: "excavator" | "wheel_loader" | "dozer" | "truck" | "grader";
  operator_id: string;
  status: "working" | "idle" | "travelling" | "off";
  pos: Pos;
  heading_deg: number;
  speed_mps: number;
  intent: "dig" | "swing_left" | "swing_right" | "dump" | "travel_forward" | "reverse" | "idle" | "push" | "grade";
  engine_on: boolean;
  engine_hours: number;
  fuel_level_pct: number;
  fuel_used_l: number;
  load_cycles: number;
  idle_min: number;
  seatbelt: "fastened" | "unfastened";
  boom_angle_deg: number;
  stick_angle_deg: number;
  swing_angle_deg: number;
  payload_kg: number;
  hydraulic_temp_c: number;
  coolant_temp_c: number;
  pitch_deg: number;
  roll_deg: number;
  tip_over_margin: number;
  bubble: "green" | "amber" | "red";
  nearest_person_m: number;
  fatigue_score: number;
  fault_codes?: string[];
  zone: string;
  task_id?: string | null;
  task_progress: number;
  task_eta_min: number;
}

export interface Pos {
  x: number;
  y: number;
  lat: number;
  lon: number;
}

/** Attached deterministically by the hub to events that have a site protocol (steps verbatim). */
export interface ProtocolRef {
  id: string;
  title: string;
  severity: string;
  steps: string[];
  escalation: string[];
  source: string;
  regulation?: RegulationRef | null;
}

export interface RegulationRef {
  citation: string;
  /** Verbatim from the public regulation text. */
  quote: string;
}

export interface Snapshot {
  /** Hub-global; strictly increasing per connection; may skip. */
  seq: number;
  /** Hub run id. A change means: drop state, wait for snapshot. */
  epoch: string;
  /** ISO-8601 UTC, millisecond precision, when the hub published. */
  hub_ts: string;
  type: "snapshot";
  ts: string;
  /** The snapshot is consistent with all reliable messages <= rseq_at. */
  rseq_at: number;
  machines?: MachineState[];
  workers?: WorkerState[];
  active_alerts?: LiveEvent[];
  environment?: Record<string, unknown>;
  sources?: SourceInfo[];
  /** since_rseq could not be honoured; fetch GET /api/events. */
  events_truncated: boolean;
}

/** Optional first frame on /ws/ingest. C's simulator sends none (it is a `sim`). */
export interface SourceHello {
  type: "source_hello";
  source_id: string;
  kind: "sim" | "twin" | "webcam" | "replay" | "fake";
  format: "contract" | "twin_snapshot";
  accepts_control: boolean;
}

export interface SourceInfo {
  source_id: string;
  kind: "sim" | "twin" | "webcam" | "replay" | "fake";
  provenance: "live" | "fake" | "replay" | "twin";
  connected: boolean;
  active: boolean;
  since: string;
  last_seen?: string | null;
  messages: number;
}

export interface SseConfirmRequired {
  action_id: string;
  tool: string;
  args?: Record<string, unknown>;
  summary: string;
  expires_at: string;
}

export interface SseDone {
}

export interface SseError {
  code: string;
  message: string;
  fallback_used: boolean;
}

export interface SseFinal {
  text: string;
  speak_text: string;
  citations?: Citation[];
  actions?: SseConfirmRequired[];
  grounded: boolean;
}

export interface SseMeta {
  turn_id: string;
  surface: "cab" | "command" | "owner" | "training" | "ar";
  mode: "live" | "cache" | "fallback";
  model?: string | null;
}

export interface SseSpecialist {
  id: string;
  label: string;
  routed_by: "rules" | "llm" | "fallback";
  confidence: number;
}

export interface SseStatus {
  state: "thinking" | "calling_tool" | "answering";
}

export interface SseToken {
  delta: string;
}

export interface SseToolCall {
  call_id: string;
  name: string;
  args?: Record<string, unknown>;
}

export interface SseToolResult {
  call_id: string;
  name: string;
  ok: boolean;
  summary: string;
  provenance: string;
  latency_ms: number;
}

export interface Utterance {
  /** Hub-global; strictly increasing per connection; may skip. */
  seq: number;
  /** Hub run id. A change means: drop state, wait for snapshot. */
  epoch: string;
  /** ISO-8601 UTC, millisecond precision, when the hub published. */
  hub_ts: string;
  /** Contiguous per epoch over reliable messages; a gap means loss. */
  rseq: number;
  type: "utterance";
  utterance_id: string;
  text: string;
  priority: "safety" | "normal" | "chatter";
  surfaces: string[];
  machine_id?: string | null;
  reason: string;
  deterministic: boolean;
  audio_url?: string | null;
}

/** One per ground worker per second. Contract section 7.4. */
export interface WorkerState {
  type: "worker_state";
  ts: string;
  worker_id: string;
  pos: Pos;
  zone: string;
}

export type LiveMessage = Hello | Snapshot | LiveMachineState | LiveWorkerState | LiveEvent | Utterance | Heartbeat;

export interface SseEventMap {
  meta: SseMeta;
  specialist: SseSpecialist;
  status: SseStatus;
  tool_call: SseToolCall;
  tool_result: SseToolResult;
  token: SseToken;
  citation: Citation;
  confirm_required: SseConfirmRequired;
  final: SseFinal;
  error: SseError;
  done: SseDone;
}
export type SseEventName = keyof SseEventMap;
