"""Screen summaries.

D's screens show many numbers that are not in the live stream - costs, carbon,
utilisation, leaderboards, skill profiles.  These functions compute them from
`data/` plus, where available, the simulator's current state.

Every function returns exactly the shape of its fixture in `fixtures/`, because
the fixtures are generated by calling these functions.  They cannot drift.

Score formulas are deliberately simple and explainable:
  safety     = 100 - 30*(belt-off ratio) - 5*(near-misses/100h) - 3*(tip-overs/100h)
  efficiency = 50*(cycles per hour / fleet median) + 50*(1 - idle ratio)
  utilisation = working minutes / engine-on minutes
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd

from simulator.config import CO2_KG_PER_LITRE, DIESEL_PRICE_INR, SPECS

DATA = Path(__file__).resolve().parent.parent / "data"

SKILLS = ("digging", "swinging", "slope_work", "safety", "fuel_efficiency")
MODULES = (
    "Pre-start inspection", "Trenching technique", "Slope and bench safety",
    "Fuel-efficient operation", "Working near ground crew", "Load handling",
)


def _iso(ts=None) -> str:
    ts = ts or datetime.now(timezone.utc)
    return pd.Timestamp(ts).strftime("%Y-%m-%dT%H:%M:%SZ")


def _clamp(v: float, lo: float = 0.0, hi: float = 100.0) -> float:
    return float(min(max(v, lo), hi))


@lru_cache(maxsize=1)
def _telemetry() -> pd.DataFrame:
    path = DATA / "telemetry.csv"
    if not path.exists():
        return pd.DataFrame()
    df = pd.read_csv(path, parse_dates=["timestamp"])
    df = df[df["task_id"] != "BRIEF"]           # the brief's rows are from 2025
    df["date"] = df["timestamp"].dt.date
    df["belt_off"] = df["seatbelt"].astype(str).str.lower() == "unfastened"
    df["working"] = df["idle_min"] <= 0
    return df


@lru_cache(maxsize=1)
def _machines() -> pd.DataFrame:
    path = DATA / "machines.csv"
    return pd.read_csv(path) if path.exists() else pd.DataFrame()


@lru_cache(maxsize=1)
def _operators() -> pd.DataFrame:
    path = DATA / "operators.csv"
    return pd.read_csv(path) if path.exists() else pd.DataFrame()


@lru_cache(maxsize=1)
def _incidents() -> pd.DataFrame:
    path = DATA / "incidents.csv"
    if not path.exists():
        return pd.DataFrame()
    df = pd.read_csv(path, parse_dates=["timestamp"])
    df["date"] = df["timestamp"].dt.date
    return df


def clear_cache() -> None:
    """Call after regenerating `data/`."""
    for fn in (_telemetry, _machines, _operators, _incidents):
        fn.cache_clear()


# --------------------------------------------------------------------------
# per-day aggregates, the basis for most of the screens
# --------------------------------------------------------------------------

def _daily() -> pd.DataFrame:
    t = _telemetry()
    if t.empty:
        return pd.DataFrame()
    g = t.groupby(["date", "machine_id", "operator_id"], as_index=False).agg(
        fuel_l=("fuel_used_l", "sum"),
        cycles=("load_cycles", "sum"),
        idle_min=("idle_min", "sum"),
        belt_off_min=("belt_off", "sum"),
        minutes=("timestamp", "count"),
        mean_hyd=("hydraulic_temp_c", "mean"),
    )
    g["working_min"] = g["minutes"] - g["idle_min"]
    g["utilization_pct"] = (g["working_min"] / g["minutes"] * 100).round(1)
    g["idle_pct"] = (g["idle_min"] / g["minutes"] * 100).round(1)
    g["idle_cost_inr"] = g.apply(
        lambda r: _idle_cost(r["machine_id"], r["idle_min"]), axis=1
    ).round(0)
    return g


def _idle_cost(machine_id: str, idle_min: float) -> float:
    machines = _machines()
    model = "320"
    if not machines.empty:
        row = machines[machines["machine_id"] == machine_id]
        if len(row):
            model = str(row.iloc[0]["model"])
    spec = SPECS.get(model)
    rate = spec.idle_fuel_lph if spec else 4.0
    return idle_min / 60.0 * rate * DIESEL_PRICE_INR


# --------------------------------------------------------------------------
# /command KPI bar
# --------------------------------------------------------------------------

def fleet_kpis(world_snapshot: dict | None = None) -> dict:
    """Top-of-screen numbers for the site manager.

    Uses the live simulator snapshot when one is passed, and falls back to the
    most recent day of history so the screen is never blank.
    """
    daily = _daily()
    machines = _machines()
    total_machines = int(len(machines)) if not machines.empty else 10

    if daily.empty:
        today = pd.DataFrame()
    else:
        today = daily[daily["date"] == daily["date"].max()]

    fuel_today = float(today["fuel_l"].sum()) if len(today) else 0.0
    idle_cost = float(today["idle_cost_inr"].sum()) if len(today) else 0.0
    utilization = float(today["utilization_pct"].mean()) if len(today) else 0.0

    incidents = _incidents()
    near_misses = 0
    alerts = 0
    critical = 0
    if not incidents.empty:
        latest_day = incidents["date"].max()
        day_rows = incidents[incidents["date"] == latest_day]
        alerts = int(len(day_rows))
        critical = int((day_rows["severity"] == "critical").sum())
        near_misses = int(day_rows["type"].isin(["proximity", "v2v"]).sum())

    active = total_machines - 1
    risk = {"score": 42, "level": "medium"}

    if world_snapshot:
        states = world_snapshot.get("machines", [])
        if states:
            active = sum(1 for s in states if s.get("engine_on"))
            fuel_today = round(sum(float(s.get("fuel_used_l", 0)) for s in states), 1)
            idle_cost = round(sum(
                _idle_cost(s["machine_id"], float(s.get("idle_min", 0))) for s in states
            ))
            working = sum(1 for s in states if s.get("status") == "working")
            engine_on = max(sum(1 for s in states if s.get("engine_on")), 1)
            utilization = round(working / engine_on * 100, 1)
        env = world_snapshot.get("environment", {})
        events = world_snapshot.get("recent_events", [])
        if events:
            alerts = len(events)
            critical = sum(1 for e in events if e.get("severity") == "critical")
            near_misses = sum(
                1 for e in events
                if e.get("event") in ("proximity_alert", "v2v_collision_risk")
            )
        from .risk import get_working_risk
        risk = get_working_risk(
            weather=env.get("weather", "clear"),
            temperature_c=env.get("temperature_c", 33.0),
            visibility_m=env.get("visibility_m", 10_000.0),
            ground=env.get("ground", "dry"),
            hours_on_shift=env.get("hours_on_shift", 0.0),
        )
        risk = {"score": risk["score"], "level": risk["level"]}

    return {
        "ts": _iso(),
        "active_machines": int(active),
        "total_machines": total_machines,
        "alerts_today": int(alerts),
        "critical_alerts_today": int(critical),
        "utilization_pct": round(utilization),
        "fuel_today_l": round(fuel_today, 1),
        "idle_cost_today_inr": int(idle_cost),
        "near_misses_today": int(near_misses),
        "working_risk": risk,
    }


# --------------------------------------------------------------------------
# /owner
# --------------------------------------------------------------------------

def utilization_series(days: int = 30) -> list[dict]:
    """Per-day utilisation, fuel and idle, fleet-wide and per machine."""
    daily = _daily()
    if daily.empty:
        return []
    dates = sorted(daily["date"].unique())[-days:]
    out = []
    for d in dates:
        rows = daily[daily["date"] == d]
        out.append({
            "date": str(d),
            "utilization_pct": round(float(rows["utilization_pct"].mean()), 1),
            "fuel_l": round(float(rows["fuel_l"].sum()), 1),
            "idle_pct": round(float(rows["idle_pct"].mean()), 1),
            "idle_cost_inr": int(rows["idle_cost_inr"].sum()),
            "cycles": int(rows["cycles"].sum()),
            "per_machine": [
                {
                    "machine_id": r["machine_id"],
                    "utilization_pct": round(float(r["utilization_pct"]), 1),
                    "fuel_l": round(float(r["fuel_l"]), 1),
                    "idle_pct": round(float(r["idle_pct"]), 1),
                }
                for _, r in rows.iterrows()
            ],
        })
    return out


def owner_summary(days: int = 7) -> dict:
    """Cost, carbon and utilisation for the machine owner."""
    series = utilization_series(days)
    if not series:
        return {
            "ts": _iso(), "days": days, "fuel_spend_inr": 0, "idle_cost_inr": 0,
            "co2_kg": 0, "utilization_pct": 0, "daily": [], "top_anomalies": [],
        }
    fuel_l = sum(d["fuel_l"] for d in series)
    idle_cost = sum(d["idle_cost_inr"] for d in series)

    try:
        from .anomaly import get_anomalies
        top = get_anomalies(since_hours=days * 24)[:3]
    except Exception:
        top = []

    return {
        "ts": _iso(),
        "days": days,
        "fuel_l": round(fuel_l, 1),
        "fuel_spend_inr": int(fuel_l * DIESEL_PRICE_INR),
        "idle_cost_inr": int(idle_cost),
        "idle_cost_share_pct": round(
            idle_cost / max(fuel_l * DIESEL_PRICE_INR, 1) * 100, 1
        ),
        "co2_kg": round(fuel_l * CO2_KG_PER_LITRE, 1),
        "utilization_pct": round(
            float(np.mean([d["utilization_pct"] for d in series])), 1
        ),
        "cycles": sum(d["cycles"] for d in series),
        "daily": series,
        "top_anomalies": top,
    }


# --------------------------------------------------------------------------
# leaderboard and training profiles
# --------------------------------------------------------------------------

def _operator_stats() -> pd.DataFrame:
    daily = _daily()
    if daily.empty:
        return pd.DataFrame()
    stats = daily.groupby("operator_id", as_index=False).agg(
        fuel_l=("fuel_l", "sum"), cycles=("cycles", "sum"),
        idle_min=("idle_min", "sum"), belt_off_min=("belt_off_min", "sum"),
        minutes=("minutes", "sum"), working_min=("working_min", "sum"),
    )
    stats["idle_ratio"] = stats["idle_min"] / stats["minutes"]
    stats["belt_off_ratio"] = stats["belt_off_min"] / stats["minutes"]
    stats["hours"] = stats["minutes"] / 60.0
    stats["cycles_per_hour"] = stats["cycles"] / stats["hours"].clip(lower=1e-6)

    incidents = _incidents()
    counts = {}
    if not incidents.empty:
        for op, rows in incidents.groupby("operator_id"):
            counts[op] = {
                "near_miss": int(rows["type"].isin(["proximity", "v2v"]).sum()),
                "tip_over": int((rows["type"] == "tip_over").sum()),
            }
    stats["near_misses"] = stats["operator_id"].map(
        lambda o: counts.get(o, {}).get("near_miss", 0)
    )
    stats["tip_overs"] = stats["operator_id"].map(
        lambda o: counts.get(o, {}).get("tip_over", 0)
    )

    # A truck driver's loads per hour and an excavator operator's cycles per
    # hour are different units.  Efficiency is therefore scored against the
    # median for the *same machine type*, or everyone on a high-cycle machine
    # pins at 100 and the leaderboard says nothing.
    machines = _machines()
    type_by_machine = (
        dict(zip(machines["machine_id"], machines["machine_type"]))
        if not machines.empty else {}
    )
    daily_machine = daily.groupby("operator_id")["machine_id"].first()
    stats["machine_type"] = stats["operator_id"].map(
        lambda o: type_by_machine.get(daily_machine.get(o, ""), "excavator")
    )
    stats["peer_median_cph"] = stats.groupby("machine_type")["cycles_per_hour"].transform(
        "median"
    ).clip(lower=1e-6)
    return stats


def leaderboard() -> list[dict]:
    """Safety and efficiency scores per operator, ranked."""
    stats = _operator_stats()
    operators = _operators()
    if stats.empty:
        return []

    names = dict(zip(operators["operator_id"], operators["name"])) if not operators.empty else {}

    rows = []
    for _, s in stats.iterrows():
        per_100h = 100.0 / max(s["hours"], 1e-6)
        safety = _clamp(
            100
            - 30 * s["belt_off_ratio"]
            - 5 * (s["near_misses"] * per_100h)
            - 3 * (s["tip_overs"] * per_100h)
        )
        efficiency = _clamp(
            50 * (s["cycles_per_hour"] / s["peer_median_cph"]) + 50 * (1 - s["idle_ratio"])
        )
        rows.append({
            "operator_id": s["operator_id"],
            "name": names.get(s["operator_id"], s["operator_id"]),
            "safety_score": round(safety),
            "efficiency_score": round(efficiency),
            "seatbelt_compliance_pct": round((1 - s["belt_off_ratio"]) * 100, 1),
            "idle_pct": round(s["idle_ratio"] * 100, 1),
            "cycles_per_hour": round(s["cycles_per_hour"], 1),
            "machine_type": s["machine_type"],
            "near_misses": int(s["near_misses"]),
            "hours": round(s["hours"], 1),
        })

    rows.sort(key=lambda r: (r["safety_score"] + r["efficiency_score"]), reverse=True)
    for i, r in enumerate(rows, start=1):
        r["rank"] = i
        r["trend"] = "up" if i <= len(rows) / 3 else ("down" if i > 2 * len(rows) / 3 else "flat")
    return rows


def training_profiles() -> list[dict]:
    """Skill levels per operator, plus what to train next."""
    board = {r["operator_id"]: r for r in leaderboard()}
    operators = _operators()
    if operators.empty:
        return []

    out = []
    for _, op in operators.iterrows():
        row = board.get(op["operator_id"])
        base = {"novice": 45, "intermediate": 68, "expert": 86}[op["skill"]]
        safety = row["safety_score"] if row else base
        efficiency = row["efficiency_score"] if row else base

        skills = {
            "digging": _clamp(base + (efficiency - 70) * 0.35),
            "swinging": _clamp(base + (efficiency - 70) * 0.25 - 3),
            "slope_work": _clamp(base - 6 + (safety - 80) * 0.3),
            "safety": _clamp(safety),
            "fuel_efficiency": _clamp(
                base + (100 - (row["idle_pct"] if row else 25)) * 0.15 - 8
            ),
        }
        skills = {k: round(v) for k, v in skills.items()}
        weakest = min(skills, key=skills.get)
        completed = max(0, int((base - 40) / 12))

        out.append({
            "operator_id": op["operator_id"],
            "name": op["name"],
            "skill": op["skill"],
            "years_experience": float(op["years_experience"]),
            "skills": skills,
            "overall": round(float(np.mean(list(skills.values())))),
            "completed_modules": list(MODULES[:completed]),
            "recommended_next_module": {
                "digging": "Trenching technique",
                "swinging": "Load handling",
                "slope_work": "Slope and bench safety",
                "safety": "Working near ground crew",
                "fuel_efficiency": "Fuel-efficient operation",
            }[weakest],
            "weakest_skill": weakest,
        })
    out.sort(key=lambda r: r["overall"], reverse=True)
    return out


# --------------------------------------------------------------------------
# incidents and heatmaps
# --------------------------------------------------------------------------

def incident_index() -> list[dict]:
    """Incident list; `has_replay` marks the few with full 60-second tracks."""
    incidents = _incidents()
    if incidents.empty:
        return []
    track_dir = DATA / "incident_tracks"
    have = {p.stem for p in track_dir.glob("*.json")} if track_dir.exists() else set()

    out = []
    for _, r in incidents.iterrows():
        out.append({
            "incident_id": r["incident_id"],
            "ts": pd.Timestamp(r["timestamp"]).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "machine_id": r["machine_id"],
            "operator_id": r["operator_id"],
            "type": r["type"],
            "severity": r["severity"],
            "zone": r["zone"],
            "x": float(r["x"]),
            "y": float(r["y"]),
            "weather": r["weather"],
            "description": r["description"],
            "has_replay": r["incident_id"] in have,
        })
    out.sort(key=lambda r: r["ts"], reverse=True)
    return out


def heatmap_points(kind: str = "near_miss") -> list[dict]:
    """Points for A's heatmap layer: [{x, y, weight}]."""
    if kind == "near_miss":
        incidents = _incidents()
        if incidents.empty:
            return []
        rows = incidents[incidents["type"].isin(["proximity", "v2v"])]
        weight = {"critical": 1.0, "high": 0.75, "medium": 0.5, "low": 0.25}
        return [
            {"x": round(float(r["x"]), 1), "y": round(float(r["y"]), 1),
             "weight": weight.get(r["severity"], 0.5)}
            for _, r in rows.iterrows()
        ]

    if kind == "idle":
        # idle is not positional in the historical data, so attribute each
        # machine's idle minutes to the zone it works in
        from simulator.config import FLEET
        from simulator.site import zone_by_id

        daily = _daily()
        if daily.empty:
            return []
        totals = daily.groupby("machine_id")["idle_min"].sum()
        peak = float(totals.max()) or 1.0
        points = []
        rng = np.random.default_rng(42)
        for entry in FLEET:
            idle = float(totals.get(entry.machine_id, 0.0))
            if idle <= 0:
                continue
            zone = zone_by_id(entry.home_zone if entry.home_zone != "road" else "A")
            cx, cy = zone.centre
            for _ in range(8):
                points.append({
                    "x": round(float(cx + rng.normal(0, 18)), 1),
                    "y": round(float(cy + rng.normal(0, 18)), 1),
                    "weight": round(idle / peak, 2),
                })
        return points

    raise ValueError(f"unknown heatmap kind {kind!r}")
