"""Contracts codegen: Pydantic -> JSON Schema -> TypeScript, plus an additive-only guard.

    uv run python -m copilot.contracts.codegen write   # make contracts
    uv run python -m copilot.contracts.codegen check   # make contracts-check

No npm or network dependency: the TypeScript is produced by the small generator below.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from copilot.config import REPO_DIR
from copilot.contracts import assistant as a
from copilot.contracts import models as m

HERE = Path(__file__).resolve().parent
SCHEMA_PATH = HERE / "schema.json"
MANIFEST_PATH = HERE / "manifest.json"
TS_PATH = REPO_DIR / "web" / "lib" / "stream" / "contracts.gen.ts"
CHANGELOG_PATH = REPO_DIR / "docs" / "CONTRACT_CHANGES.md"

MODELS: tuple[type[BaseModel], ...] = (
    *m.LIVE_MESSAGES,
    *m.INGEST_MESSAGES,
    *m.CONTROL_MESSAGES,
    m.SourceInfo,
    *a.ASSISTANT_MODELS,
)


# --------------------------------------------------------------------------- schema


def build_schema() -> dict[str, Any]:
    _, top = models_json_schema(
        [(model, "serialization") for model in MODELS], ref_template="#/$defs/{model}"
    )
    defs = top.get("$defs", {})
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "CAT Copilot hub contracts",
        "version": m.CONTRACT_VERSION,
        "$defs": dict(sorted(defs.items())),
    }


# --------------------------------------------------------------------------- TypeScript


def _lit(v: Any) -> str:
    return json.dumps(v)


def ts_type(s: dict[str, Any]) -> str:
    if not s:
        return "unknown"
    if "$ref" in s:
        return s["$ref"].rsplit("/", 1)[-1]
    if "const" in s:
        return _lit(s["const"])
    if "enum" in s:
        return " | ".join(_lit(v) for v in s["enum"])
    for key in ("anyOf", "oneOf"):
        if key in s:
            parts: list[str] = []
            for sub in s[key]:
                t = ts_type(sub)
                if t not in parts:
                    parts.append(t)
            return " | ".join(parts)
    t = s.get("type")
    if isinstance(t, list):
        return " | ".join(ts_type({**s, "type": x}) for x in t)
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        if "prefixItems" in s:
            return "[" + ", ".join(ts_type(x) for x in s["prefixItems"]) + "]"
        inner = ts_type(s.get("items", {}))
        return f"({inner})[]" if " | " in inner else f"{inner}[]"
    if t == "object":
        if "properties" in s:
            return "{ " + " ".join(f"{k}: {ts_type(v)};" for k, v in s["properties"].items()) + " }"
        ap = s.get("additionalProperties")
        if isinstance(ap, dict) and ap:
            return f"Record<string, {ts_type(ap)}>"
        return "Record<string, unknown>"
    return "unknown"


def _optional(name: str, prop: dict[str, Any], required: set[str]) -> bool:
    """Optional in TS only when the field may be absent: not required and default None/absent."""
    if name in required:
        return False
    return "default" not in prop or prop["default"] is None


def model_fields(defs: dict[str, Any]) -> dict[str, dict[str, str]]:
    out: dict[str, dict[str, str]] = {}
    for name, d in defs.items():
        if d.get("type") != "object":
            continue
        req = set(d.get("required", []))
        fields: dict[str, str] = {}
        for fname, prop in d.get("properties", {}).items():
            fields[fname] = ts_type(prop) + ("?" if _optional(fname, prop, req) else "")
        out[name] = fields
    return out


def build_ts(schema: dict[str, Any]) -> str:
    defs = schema["$defs"]
    lines = [
        "// GENERATED by `make contracts` (backend/copilot/contracts/codegen.py). Do not edit.",
        "// Canonical stream payloads come from Person C's simulator/schemas.py;",
        "// envelope + hub messages from backend/copilot/contracts. Changes are additive only.",
        "/* eslint-disable */",
        "",
        f"export const CONTRACT_VERSION = {_lit(m.CONTRACT_VERSION)};",
        f"export const EVENT_CATALOGUE = {json.dumps(list(m.ALL_EVENT_KINDS))} as const;",
        f"export const HUB_EVENT_KINDS = {json.dumps(list(m.HUB_EVENT_KINDS))} as const;",
        f"export const SEVERITIES = {json.dumps(list(m.SEVERITIES))} as const;",
        "export type EventKind = (typeof EVENT_CATALOGUE)[number];",
        "export type Severity = (typeof SEVERITIES)[number];",
        "",
    ]
    for name, d in defs.items():
        if d.get("type") == "object":
            if d.get("description"):
                lines.append("/** " + " ".join(d["description"].split()) + " */")
            lines.append(f"export interface {name} {{")
            req = set(d.get("required", []))
            for fname, prop in d.get("properties", {}).items():
                if prop.get("description"):
                    lines.append("  /** " + " ".join(prop["description"].split()) + " */")
                opt = "?" if _optional(fname, prop, req) else ""
                lines.append(f"  {fname}{opt}: {ts_type(prop)};")
            lines.append("}")
        else:
            lines.append(f"export type {name} = {ts_type(d)};")
        lines.append("")
    live = [mdl.__name__ for mdl in m.LIVE_MESSAGES]
    lines.append(f"export type LiveMessage = {' | '.join(live)};")
    lines.append("")
    lines.append("export interface SseEventMap {")
    for ev, mdl in a.SSE_EVENTS.items():
        lines.append(f"  {ev}: {mdl.__name__};")
    lines.append("}")
    lines.append("export type SseEventName = keyof SseEventMap;")
    lines.append("")
    return "\n".join(lines)


def build_manifest(schema: dict[str, Any]) -> dict[str, Any]:
    flat: dict[str, str] = {}
    for model, fields in model_fields(schema["$defs"]).items():
        for f, t in fields.items():
            flat[f"{model}.{f}"] = t
    return {"version": m.CONTRACT_VERSION, "fields": dict(sorted(flat.items()))}


# --------------------------------------------------------------------------- guards


def _members(t: str) -> tuple[set[str], bool]:
    opt = t.endswith("?")
    return {p.strip() for p in t.rstrip("?").split(" | ")}, opt


def additive_violations(old: dict[str, str], new: dict[str, str]) -> list[str]:
    """Removed fields and retyped fields are violations; new fields and enum widening are fine."""
    problems: list[str] = []
    for key, old_t in old.items():
        if key not in new:
            problems.append(f"removed: {key} ({old_t})")
            continue
        new_t = new[key]
        if new_t == old_t:
            continue
        old_m, old_opt = _members(old_t)
        new_m, new_opt = _members(new_t)
        literal = all(re.fullmatch(r'"[^"]*"', x) for x in old_m | new_m)
        if literal and old_m <= new_m and old_opt == new_opt:
            continue  # enum widened
        problems.append(f"retyped: {key}: {old_t} -> {new_t}")
    return problems


def changelog_has(version: str) -> bool:
    if not CHANGELOG_PATH.exists():
        return False
    return re.search(rf"^## {re.escape(version)}\b", CHANGELOG_PATH.read_text(), re.M) is not None


def _git_head_manifest() -> dict[str, Any] | None:
    rel = MANIFEST_PATH.relative_to(REPO_DIR).as_posix()
    try:
        out = subprocess.run(
            ["git", "show", f"HEAD:{rel}"], cwd=REPO_DIR, capture_output=True, text=True, check=True
        ).stdout
        return json.loads(out)
    except (subprocess.CalledProcessError, json.JSONDecodeError, FileNotFoundError):
        return None


def _dump(obj: Any) -> str:
    return json.dumps(obj, indent=2, sort_keys=False) + "\n"


def render() -> dict[Path, str]:
    schema = build_schema()
    return {
        SCHEMA_PATH: _dump(schema),
        MANIFEST_PATH: _dump(build_manifest(schema)),
        TS_PATH: build_ts(schema),
    }


def write() -> int:
    files = render()
    new_manifest = json.loads(files[MANIFEST_PATH])
    if MANIFEST_PATH.exists():
        old = json.loads(MANIFEST_PATH.read_text())
        problems = additive_violations(old["fields"], new_manifest["fields"])
        if problems:
            print("Refusing to write non-additive contract changes:\n  " + "\n  ".join(problems))
            return 1
        if old["fields"] != new_manifest["fields"] and old["version"] == new_manifest["version"]:
            print(f"Contract changed but CONTRACT_VERSION is still {old['version']}: bump it.")
            return 1
    if not changelog_has(m.CONTRACT_VERSION):
        print(f"docs/CONTRACT_CHANGES.md has no '## {m.CONTRACT_VERSION}' entry.")
        return 1
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"wrote {path.relative_to(REPO_DIR)}")
    return 0


def check() -> int:
    failures: list[str] = []
    for path, text in render().items():
        if not path.exists() or path.read_text() != text:
            failures.append(f"stale: {path.relative_to(REPO_DIR)} (run `make contracts`)")
    new_manifest = json.loads(render()[MANIFEST_PATH])
    head = _git_head_manifest()
    if head is not None:
        failures += additive_violations(head["fields"], new_manifest["fields"])
        if head["fields"] != new_manifest["fields"] and head["version"] == new_manifest["version"]:
            failures.append(f"contract changed since HEAD but version is still {head['version']}")
    if not changelog_has(m.CONTRACT_VERSION):
        failures.append(f"docs/CONTRACT_CHANGES.md lacks '## {m.CONTRACT_VERSION}'")
    if failures:
        print("contracts-check FAILED:\n  " + "\n  ".join(failures))
        return 1
    n = len(new_manifest["fields"])
    print(f"contracts-check ok: v{m.CONTRACT_VERSION}, {n} fields, generated files fresh")
    return 0


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    sys.exit(write() if cmd == "write" else check())
